apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: example-ui
        image: example-ui
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4200
        readinessProbe:
          httpGet:
            path: /
            port: 4200
          initialDelaySeconds: 5
          periodSeconds: 3
          timeoutSeconds: 3
          failureThreshold: 10

        # resources:
        #   requests:
        #     memory: "250Mi"
        #     cpu: "200m"
        #   limits:
        #     memory: "1Gi"
        #     cpu: "500m"
